<?php
defined( 'ABSPATH' ) || exit;

// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Template files are included inside class methods, so render variables are local.
// Rendered as the Documentation tab inside help-center.php, which already
// provides the page wrapper and header.
?>
    <div class="gatetouch-help-center">
        <!-- Sidebar Navigation -->
        <div class="rhc-sidebar">
            <div class="rhc-search">
                <input type="text" id="rhc-search-input" placeholder="Search documentation...">
            </div>
            <div class="rhc-nav" id="rhc-nav-container">
                <!-- Nav items generated by JS -->
            </div>
        </div>

        <!-- Main Content Area -->
        <div class="rhc-content-area" id="rhc-content-area">
            <div class="rhc-empty-state">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path></svg>
                <h2><?php esc_html_e( 'Loading Documentation...', 'gatetouch-ai-seo' ); ?></h2>
                <p><?php esc_html_e( 'Please wait while we prepare the knowledge base.', 'gatetouch-ai-seo' ); ?></p>
            </div>
        </div>
    </div>
